<form id="mall_form" class="form-horizontal" action="/base/save" method="post" enctype="multipart/form-data">
    <div class="box-body">
        <div class="form-group has-success required_box">
            <label for="" class="col-sm-2 control-label"><i class="fa fa-check-circle">(必填)</i>商城名称</label>
            <div class="col-sm-5">
                <input value="<?=$data['mallName']?>" type="text" name="mallName" maxlength="20" class="form-control" id="" placeholder="商城名称">
            </div>
        </div>
        <div class="form-group has-success required_box">
            <label for="" class="col-sm-2 control-label"><i class="fa fa-check-circle">(必填)</i>小程序图标</label>
            <div class="col-sm-5">
                <input name="logo" id="input_file" type="file" size-limit="500" >
                <img id="img_file" src="<?=$data['logo']?>" height="50" />
                <span class="text-red" style="display: none">图片大小不能超过500kb</span>
            </div>
            <label class="control-label" data-toggle="tooltip" title="" data-original-title="请上传500kb以内；建议图片尺寸为750px*630px；格式为jpeg,jpg,png的图片"><i class="fa fa-info-circle"></i><label/>
        </div>
        <div class="form-group">
            <label for="" class="col-sm-2 control-label">运费</label>
            <div class="col-sm-5">
                <input value="<?=$data['freeFee']?>" name="freeFee" type="number" oninput="this.value=this.value.replace(/\D/g,'')" class="form-control" id="" placeholder="运费">
            </div>
            <label for="" class="control-label text-green">单笔订单满 免运费</label>
        </div>
        <div class="form-group">
            <label for="" class="col-sm-2 control-label">设置高于等于</label>
            <div class="col-sm-5">
                <select class="form-control" name="crmFreeLevel">
                    <option value="">选择等级</option>
                    <?php foreach ($cardCats as $k=>$v):?>
                        <option value="<?=$k?>" <?=$k==$data['crmFreeLevel']?'selected':''?>><?=$v?></option>
                    <?php endforeach;?>
                </select>
            </div>
            <label for="" class="control-label">会员将会免运费</label>
        </div>
        <div class="form-group">
            <label for="" class="col-sm-2 control-label">商城介绍</label>
            <div class="col-sm-10">
                <textarea class="form-control" name="descr"><?=$data['descr']?></textarea>
            </div>
        </div>
        <div class="form-group has-success required_box">
            <label for="" class="col-sm-2 control-label"><i class="fa fa-check-circle">(必填)</i>客服电话</label>
            <div class="col-sm-5">
                <input value="<?=$data['phone']?>" type="number" name="phone" class="form-control" id="" placeholder="客服电话">
            </div>
        </div>
        <div class="form-group">
            <label for="" class="col-sm-2 control-label">商城服务</label>
            <div class="col-sm-10" id="editor"><?=$data['service']?></div>
            <div style="display:none">
                <textarea name="service" value="<?=$data['service']?>"></textarea>
            </div>
        </div>
    </div>
    <!-- /.box-body -->
    <div class="box-footer">
        <button type="submit" class="btn btn-primary save_btn">提交</button>
        <?php if (!empty($data)):?>
            <input type="hidden" name="id" value="<?=$data['id']?>">
            <input type="hidden" name="logo_old" value="<?=$data['logo']?>">
        <?php endif;?>
    </div>
    <!-- /.box-footer -->
</form>

<script>
    var E = window.wangEditor;
    var editor = new E('#editor');
    editor.customConfig.uploadImgServer = '/product/uploadImage'; //上传URL
    editor.customConfig.uploadImgMaxSize = 1 * 1024 * 1024;
    editor.customConfig.uploadImgMaxLength = 10;
    editor.customConfig.uploadFileName = 'myFileName';
    editor.customConfig.uploadImgHooks = {
        customInsert: function (insertImg, result) {

            // 图片上传并返回结果，自定义插入图片的事件（而不是编辑器自动插入图片！！！）
            // insertImg 是插入图片的函数，editor 是编辑器对象，result 是服务器端返回的结果

            // 举例：假如上传图片成功后，服务器端返回的是 {url:'....'} 这种格式，即可这样插入图片：
            var url = result.data;
            //insert();
            insertImg(url);
            //insertImg('https://ss0.bdstatic.com/5aV1bjqh_Q23odCf/static/superman/img/logo/bd_logo1_31bdc765.png');

            // result 必须是一个 JSON 格式字符串！！！否则报错
        }
    };
    editor.create();
</script>
