<?php include APP_PATH . '/views/'.strtolower(APP_NAME).'/include/head.phtml'; ?>
<div class="content-wrapper">
    <!-- Content Header (页眉) -->
    <section class="content-header">
        <h1>
            商城设置
            <small>运费模板</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-gears"></i> 商城设置</a></li>
            <li class="active">运费模板</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="nav-tabs-custom">
                    <ul class="nav nav-tabs" finish-status="true">
                        <li><a href="/tpl/list">模板列表</a></li>
                        <li class="tabs-modify" style="display: none"><a href="/tpl/modify">新增模板</a></li>
                    </ul>

                    <div class="box-body">
                        <div class="col-md-3 overlay" id="refresh">
                            <i class="fa fa-spinner fa-spin"></i>
                        </div>
                        <div class="-box-content">

                        </div>
                    </div>
                </div>
                <!-- /.box -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>
    <!-- /.content -->
</div>
<?php include APP_PATH . '/views/'.strtolower(APP_NAME).'/include/foot.phtml'; ?>
<script>
    $(function () {
        // 表单提交
        $(".-box-content").on('click', '.save_btn', function () {
            var fromObj = $("#mall_form"), li = $(this).attr('li');
            if(checkFormRequired(fromObj)){
                var url = fromObj.attr('action'), postData = new FormData(fromObj[0]);
                if(url && postData){
                    $.ajax({
                        url: url,
                        type:'POST',
                        cache:false,
                        data: postData,
                        processData:false,
                        contentType:false
                    }).done(function (data) {
                        if (data.code == 200){
                            if(li){
                                $(".nav-tabs li").eq(li).click();
                            }else {
                                $(".nav-tabs .active").removeClass("active").click().show();
                            }
                        } else{
                            alert(data.msg);
                        }
                    }).fail(function (data) {
                        alert('请求失败');
                    });
                }
            }
            return false;
        });

        // 检测必填字段
        function checkFormRequired(obj){
            if(!obj) return true;
            var inx = 0;
            obj.find(".required_box").each(function () {
                var self = $(this), input = self.find('input').length?self.find('input'):self.find('select');
                var check = self.attr('check'), val = input.val();
                if(!val){
                    var type = input.attr('type'),
                        src = input.parent().find('img').attr('src');
                    if (type == 'file' && src) {
                        self.removeClass("has-error");
                    }else {
                        self.addClass("has-error");
                        if (inx == 0) {
                            input.focus();
                        }
                        inx++;
                    }
                }else {
                    self.removeClass("has-error");
                }
            });

            return (inx==0)?true:false;
        }

        // 编辑或添加广告按钮操作
        $(".-box-content").on('click','.edit_tpl, .add_tpl',function () {
            var url = $(this).attr('url'), title = $(this).attr('title');
            if(!url) { //编辑
                var form = $(this).parent().find('.edit_form'),
                    formData = form.serialize(), action = form.attr('action');
                url = action + "?" + formData;
            }
            if(title){
                $(".tabs-modify").find("a").text(title);
            }
            $(".tabs-modify").find("a").attr("href", url);
            $(".tabs-modify").click().show();
        });

        // 收起、展开
        $(".-box-content").on('click', '.opt_btn', function () {
            var text = $(this).text(), opt_obj = $(this).attr('opt_obj');
            if(text == '收起'){
                $(this).text('展开');
                $(opt_obj).fadeOut();
            }else{
                $(this).text('收起');
                $(opt_obj).fadeIn();
            }
        })

        // 计价方式切换
        $(".-box-content").on('click', '.type_check input',function () {
            var val = $(this).val(), tr_body = tr_html = "";
            tr_html += "<th>可配送区域</th>";
            tr_body += "<tr>";
            if(val == 1){
                tr_html += "<th>首件（个）</th>";
                tr_html += "<th>运费（元）</th>";
                tr_html += "<th>续件（个）</th>";
                tr_html += "<th>运费（元）</th>";
            }else if(val == 2){
                tr_html += "<th>首重（Kg）</th>";
                tr_html += "<th>运费（元）</th>";
                tr_html += "<th>续重（Kg）</th>";
                tr_html += "<th>运费（元）</th>";
            }
            $('.tr_menu').html(tr_html);
            if(val == 1 || val == 2){
                tr_body += "<td><input style=\"width: 100px\" type=\"text\"></td>";
                tr_body += "<td><input style=\"width: 60px\" type=\"number\" oninput=\"this.value=this.value.replace(/\\D/g,'')\"></td>";
                tr_body += "<td><input style=\"width: 60px\" type=\"text\" oninput=\"this.value=this.value.match(/\\d+(\\.\\d{0,2})?/)?this.value.match(/\\d+(\\.\\d{0,2})?/)[0]:''\"></td>"
                tr_body += "<td><input style=\"width: 60px\" type=\"number\" oninput=\"this.value=this.value.replace(/\\D/g,'')\"></td>";
                tr_body += "<td><input style=\"width: 60px\" type=\"text\" oninput=\"this.value=this.value.match(/\\d+(\\.\\d{0,2})?/)?this.value.match(/\\d+(\\.\\d{0,2})?/)[0]:''\"></td>"
            }else{
                tr_body += "<td><input type=\"text\"></td>";
            }
            tr_body += "</tr>";
            if(val == 1 || val == 2){
                tr_body += "<tr><td><button type=\"button\" class=\"btn btn-default add_tr\"><i class=\"fa fa-plus\">增加配送区域</i></button></td></tr>";
            }
            $('.tr_body').html(tr_body);
        });

        // 增加配送区域
        $(".-box-content").on('click','.add_tr',function () {
            var tr_body = $(this).parents('.tr_body'),
                this_tr = $(this).parents('tr'),
                tr_new = tr_body.find('tr').eq(0).clone(true),
                td = tr_new.find('td').eq(0),
                td_html = td.html()+"<button type=\"button\" class=\"btn btn-danger del_tr\"><i class=\"fa fa-minus\">删除</i></button>";
            td.html(td_html);
            tr_new.find('input').val('');
            this_tr.before(tr_new);
        });
        // 删除
        $(".-box-content").on('click','.del_tr',function () {
            $(this).parents('tr').remove();
        });
    })
</script>