<div class="box-header with-border label-primary"><b>基本信息</b></div>
<div class="box-body">
    <div class="form-horizontal">
        <div class="form-group has-success required_box">
            <label for="" class="col-sm-2 control-label"><i class="fa fa-check-circle">(必填)</i>折扣名称</label>
            <div class="col-sm-3">
                <input value="<?=$data['name']?>" type="text" name="name" maxlength="6" class="form-control" id="" placeholder="折扣名称">
            </div>
            <label class="control-label" data-toggle="tooltip" title="" data-original-title="名称长度不可超过6个字符"><i class="fa fa-info-circle"></i></label>
        </div>
        <div class="form-group has-success required_box">
            <label for="" class="col-sm-2 control-label"><i class="fa fa-check-circle">(必填)</i>折扣</label>
            <div class="col-sm-2">
                <input type="number" name="name" class="form-control" id="" placeholder="值范围(1~10)">
            </div>
            <div class="col-sm-2">
                <select class="form-control" name="cid">
                    <option value="0">选择会员等级</option>
                    <?php if(!empty($cardCats)):?>
                    <?php foreach ($cardCats as $k=>$v):?>
                    <option value="<?=$k?>"><?=$v?></option>
                    <?php endforeach;?>
                    <?php endif;?>
                </select>
            </div>
            <div class="col-sm-2">
                <button type="button" class="btn btn-default add_btn"><i class="fa fa-plus">增加折扣</i></button>
            </div>
            <label class="control-label one_label" data-toggle="tooltip" title="" data-original-title="低等级折扣兼顾高等级会员价，即设置折扣后高于该等级会员都将会有折扣"><i class="fa fa-info-circle"></i></label>
            <label class="control-label text-red" style="display: none;">折扣值范围只能1~10</label>
        </div>
    </div>
</div>

<?php if(!empty($disId)):?>
<div class="discount_info yes_discount" url="/sales/discount/<?=$disId?>">
    <div class="box-header with-border label-primary"><b>已添加折扣的商品信息</b></div>
    <div class="box-body">
        <div class="search-body" style="margin-bottom: 15px;">
            <form method="post" action="" class="search-form">
                <div class="row">
                    <div class="col-xs-3">
                        <div class="input-group">
                            <div class="input-group-btn">
                                <button type="button" class="btn btn-default">商品名称</button>
                            </div><!-- /btn-group -->
                            <input type="text" class="form-control" name='id' value="" placeholder="商品名称">
                        </div>
                    </div>
                    <div class="col-xs-3">
                        <div class="input-group">
                            <div class="input-group-btn">
                                <button type="button" class="btn btn-default">商品ID</button>
                            </div><!-- /btn-group -->
                            <input type="text" class="form-control" name='id' value="" placeholder="商品ID">
                        </div>
                    </div>
                    <div class="col-xs-3">
                        <div class="input-group">
                            <div class="input-group-btn">
                                <button type="button" class="btn btn-default">商品分类</button>
                            </div><!-- /btn-group -->
                            <select class="form-control" name="cid">
                                <option value="">选择商品分类</option>
                                <?php if(!empty($cats)):?>
                                    <?php foreach ($cats as $_k=>$_v):?>
                                        <option value="<?=$_k?>"><?=$_v?></option>
                                    <?php endforeach;?>
                                <?php endif;?>
                            </select>
                        </div>
                    </div>
                    <div class="col-xs-3">
                        <button type="reset" class="btn btn-default">重置</button>
                        <button type="button" class="btn btn-success search_btn">搜索</button>
                    </div>
                </div>
            </form>
        </div>
        <div class="discount_body">
            <div class="col-md-3 overlay" id="refresh">
                <i class="fa fa-spinner fa-spin"></i>
            </div>
        </div>
    </div>
</div>
<?php endif;?>

<div class="discount_info no_discount" url="/sales/discount/0">
    <div class="box-header with-border label-primary"><b>可添加折扣的商品信息</b></div>
    <div class="box-body">
        <div class="search-body" style="margin-bottom: 15px;">
            <form method="post" action="" class="search-form">
                <div class="row">
                    <div class="col-xs-3">
                        <div class="input-group">
                            <div class="input-group-btn">
                                <button type="button" class="btn btn-default">商品名称</button>
                            </div><!-- /btn-group -->
                            <input type="text" class="form-control" name='id' value="" placeholder="商品名称">
                        </div>
                    </div>
                    <div class="col-xs-3">
                        <div class="input-group">
                            <div class="input-group-btn">
                                <button type="button" class="btn btn-default">商品分类</button>
                            </div><!-- /btn-group -->
                            <select class="form-control" name="cid">
                                <option value="">选择商品分类</option>
                                <?php if(!empty($cats)):?>
                                    <?php foreach ($cats as $_kk=>$_vv):?>
                                        <option value="<?=$_kk?>"><?=$_vv?></option>
                                    <?php endforeach;?>
                                <?php endif;?>
                            </select>
                        </div>
                    </div>
                    <div class="col-xs-3">
                        <button type="reset" class="btn btn-default">重置</button>
                        <button type="button" class="btn btn-success search_btn">搜索</button>
                    </div>
                </div>
            </form>
        </div>
        <table id="example1" class="table table-bordered table-striped">
            <thead>
            <tr>
                <th><input type="checkbox" id="check-all"></th>
                <th>ID</th>
                <th>商品名称</th>
                <th>分类</th>
                <th>售价</th>
            </tr>
            </thead>
            <?php if (!empty($results)):?>
                <?php foreach ($results as $k=>$v):?>
                    <tr>
                        <td><input type="checkbox" value="1336" class="id-checkbox"></td>
                        <td><?=$v['id']?></td>
                        <td title="<?=$v['name']?>"><?=$v['name']?></td>
                        <td><?=$v['discount_max'][2]*10?>（<?=$v['discount_max'][1]?>）</td>
                        <td><?=$v['discount_min'][2]*10?>（<?=$v['discount_min'][1]?>）</td>
                        <td><?=date('Y-m-d H:i:s', strtotime($v['gmtCreated']))?></td>
                    </tr>
                <?php endforeach;?>
            <?php endif;?>
        </table>
        <!--<div class="discount_body">
            <div class="col-md-3 overlay" id="refresh">
                <i class="fa fa-spinner fa-spin"></i>
            </div>
        </div>-->
    </div>
</div>

<div class="box-footer">
    <button type="submit" class="btn btn-primary">提交</button>
    <?php if (!empty($data)):?>
        <input type="hidden" name="id" value="<?=$data['id']?>">
        <input type="hidden" name="icon" id="icon_file" value="<?=$data['icon']?>">
    <?php endif;?>
</div>

<script>

</script>