<div class="box-header with-border label-primary"><b>基本信息</b></div>
<div class="box-body">
    <div class="form-horizontal">
        <div class="form-group required_box">
            <label for="" class="col-sm-3 control-label">折扣名称</label>
            <div class="col-sm-3">
                <input value="<?=$data['name']?>" type="text" name="name" maxlength="6" class="form-control" id="" placeholder="折扣名称">
            </div>
            <label class="control-label" data-toggle="tooltip" title="" data-original-title="名称长度不可超过6个字符"><i class="fa fa-info-circle"></i></label>
        </div>
        <div class="form-group required_box">
            <label for="" class="col-sm-3 control-label">折扣</label>
            <div class="col-sm-3">
                <input type="number" name="name" class="form-control" id="" placeholder="折扣值范围(1~10)">
            </div>
            <div class="col-sm-3">
                <select class="form-control" name="cid">
                    <option value="">选择会员等级</option>
                    <option value="179_">厨房用品</option>
                    <option value="117_个">测试11</option>
                    <option value="116_个">美食</option>
                    <option value="178_">jim</option>
                </select>
            </div>
            <label class="control-label" data-toggle="tooltip" title="" data-original-title="低等级折扣兼顾高等级会员价，即设置折扣后高于该等级会员都将会有折扣"><i class="fa fa-info-circle"></i></label>
        </div>
    </div>
</div>

<div class="box-header with-border label-primary"><b>已添加折扣的商品信息</b></div>
<div class="box-body">
    <div class="search-body" style="margin-bottom: 15px;">
        <form method="post" action="" class="search-form">
            <div class="row">
                <div class="col-xs-3">
                    <div class="input-group">
                        <div class="input-group-btn">
                            <button type="button" class="btn btn-default">商品名称</button>
                        </div><!-- /btn-group -->
                        <input type="text" class="form-control" name='id' value="" placeholder="商品名称">
                    </div>
                </div>
                <div class="col-xs-3">
                    <div class="input-group">
                        <div class="input-group-btn">
                            <button type="button" class="btn btn-default">商品ID</button>
                        </div><!-- /btn-group -->
                        <input type="text" class="form-control" name='id' value="" placeholder="商品ID">
                    </div>
                </div>
                <div class="col-xs-3">
                    <div class="input-group">
                        <div class="input-group-btn">
                            <button type="button" class="btn btn-default">商品分类</button>
                        </div><!-- /btn-group -->
                        <select class="form-control" name="cid">
                            <option value="">选择会员等级</option>
                            <option value="179_">厨房用品</option>
                            <option value="117_个">测试11</option>
                            <option value="116_个">美食</option>
                            <option value="178_">jim</option>
                        </select>
                    </div>
                </div>
                <div class="col-xs-3">
                    <button type="reset" class="btn btn-default">重置</button>
                    <button type="button" class="btn btn-success search_btn">搜索</button>
                </div>
            </div>
        </form>
    </div>
    <table id="example1" class="table table-bordered table-striped">
        <thead>
        <tr>
            <th>ID</th>
            <th>折扣名称</th>
            <th>最大折扣</th>
            <th>最小折扣</th>
            <th>添加时间</th>
            <th>操作</th>
        </tr>
        </thead>
        <?php if (!empty($results)):?>
            <?php foreach ($results as $k=>$v):?>
                <tr>
                    <td><?=$v['id']?></td>
                    <td title="<?=$v['name']?>"><?=$v['name']?></td>
                    <td><?=$v['discount_max'][2]*10?>（<?=$v['discount_max'][1]?>）</td>
                    <td><?=$v['discount_min'][2]*10?>（<?=$v['discount_min'][1]?>）</td>
                    <td><?=date('Y-m-d H:i:s', strtotime($v['gmtCreated']))?></td>
                    <td>
                        <div class="btn-group">
                            <form action="/cat/modify" class="edit_form">
                                <input type="hidden" name="name" value="<?=$v['name']?>">
                                <input type="hidden" name="icon" value="<?=$v['icon']?>">
                                <input type="hidden" name="order" value="<?=$v['order']?>">
                                <input type="hidden" name="hot" value="<?=$v['hot']?>">
                                <input type="hidden" name="status" value="<?=$v['status']?>">
                                <input type="hidden" name="parentCid" value="<?=$v['parentCid']?>">
                                <input type="hidden" name="id" value="<?=$v['id']?>">
                            </form>
                            <button type="button" class="btn btn-default btn-edit">编辑</button>
                            <button type="button" url="/cat/del?id=<?=$v['id']?>" class="btn btn-danger btn_del">删除</button>
                        </div>
                    </td>
                </tr>
            <?php endforeach;?>
        <?php endif;?>
    </table>
</div>

<div class="box-header with-border label-primary"><b>可添加折扣的商品信息</b></div>
<div class="box-body">
    <div class="search-body" style="margin-bottom: 15px;">
        <form method="post" action="" class="search-form">
            <div class="row">
                <div class="col-xs-3">
                    <div class="input-group">
                        <div class="input-group-btn">
                            <button type="button" class="btn btn-default">商品名称</button>
                        </div><!-- /btn-group -->
                        <input type="text" class="form-control" name='id' value="" placeholder="商品名称">
                    </div>
                </div>
                <div class="col-xs-3">
                    <div class="input-group">
                        <div class="input-group-btn">
                            <button type="button" class="btn btn-default">商品分类</button>
                        </div><!-- /btn-group -->
                        <select class="form-control" name="cid">
                            <option value="">选择会员等级</option>
                            <option value="179_">厨房用品</option>
                            <option value="117_个">测试11</option>
                            <option value="116_个">美食</option>
                            <option value="178_">jim</option>
                        </select>
                    </div>
                </div>
                <div class="col-xs-3">
                    <button type="reset" class="btn btn-default">重置</button>
                    <button type="button" class="btn btn-success search_btn">搜索</button>
                </div>
            </div>
        </form>
    </div>
    <table id="example1" class="table table-bordered table-striped">
        <thead>
        <tr>
            <th>ID</th>
            <th>折扣名称</th>
            <th>最大折扣</th>
            <th>最小折扣</th>
            <th>添加时间</th>
            <th>操作</th>
        </tr>
        </thead>
        <?php if (!empty($results)):?>
            <?php foreach ($results as $k=>$v):?>
                <tr>
                    <td><?=$v['id']?></td>
                    <td title="<?=$v['name']?>"><?=$v['name']?></td>
                    <td><?=$v['discount_max'][2]*10?>（<?=$v['discount_max'][1]?>）</td>
                    <td><?=$v['discount_min'][2]*10?>（<?=$v['discount_min'][1]?>）</td>
                    <td><?=date('Y-m-d H:i:s', strtotime($v['gmtCreated']))?></td>
                    <td>
                        <div class="btn-group">
                            <form action="/cat/modify" class="edit_form">
                                <input type="hidden" name="name" value="<?=$v['name']?>">
                                <input type="hidden" name="icon" value="<?=$v['icon']?>">
                                <input type="hidden" name="order" value="<?=$v['order']?>">
                                <input type="hidden" name="hot" value="<?=$v['hot']?>">
                                <input type="hidden" name="status" value="<?=$v['status']?>">
                                <input type="hidden" name="parentCid" value="<?=$v['parentCid']?>">
                                <input type="hidden" name="id" value="<?=$v['id']?>">
                            </form>
                            <button type="button" class="btn btn-default btn-edit">编辑</button>
                            <button type="button" url="/cat/del?id=<?=$v['id']?>" class="btn btn-danger btn_del">删除</button>
                        </div>
                    </td>
                </tr>
            <?php endforeach;?>
        <?php endif;?>
    </table>
</div>
<div class="box-footer">
    <button type="submit" class="btn btn-primary">提交</button>
    <?php if (!empty($data)):?>
        <input type="hidden" name="id" value="<?=$data['id']?>">
        <input type="hidden" name="icon" id="icon_file" value="<?=$data['icon']?>">
    <?php endif;?>
</div>

<!-- 批量设置弹窗模块 start -->
<div class="modal fade bulk_set" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Modal title</h4>
            </div>
            <div class="modal-body form-horizontal">
                <div class="form-group">
                    <label for="" class="col-sm-2 control-label">请输入</label>
                    <div class="col-sm-5">
                        <input type="text" class="form-control" id="bulk_val">
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
                <button type="button" class="btn btn-primary bulk_save" class_name="" data-dismiss="modal">保存</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<!-- 弹窗模块 end -->