<?php include APP_PATH . '/views/'.strtolower(APP_NAME).'/include/head.phtml'; ?>
<div class="content-wrapper">
    <!-- Content Header (页眉) -->
    <section class="content-header">
        <h1>
            营销
            <small>会员折扣</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-th"></i> 营销</a></li>
            <li class="active">会员折扣</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="nav-tabs-custom">
                    <ul class="nav nav-tabs" finish-status="true">
                        <li search-class="all_list"><a href="/crm/list">会员折扣</a></li>
                        <li search-class="other_list"><a href="/crm/modify">添加折扣</a></li>
                        <li class="tabs-modify" style="display: none"><a href="/crm/modify">编辑折扣</a></li>
                    </ul>

                    <div class="box-body">
                        <div class="search-body all_list">
                            <form method="post" action="" class="search-form">
                                <div class="row">
                                    <div class="col-xs-3">
                                        <div class="input-group">
                                            <div class="input-group-btn">
                                                <button type="button" class="btn btn-default">ID</button>
                                            </div><!-- /btn-group -->
                                            <input type="text" class="form-control" name='id' value="" placeholder="ID">
                                        </div>
                                    </div>
                                    <div class="col-xs-3">
                                        <div class="input-group">
                                            <div class="input-group-btn">
                                                <button type="button" class="btn btn-default">折扣名称</button>
                                            </div><!-- /btn-group -->
                                            <input type="text" class="form-control" name='name' value="" placeholder="折扣名称">
                                        </div>
                                    </div>
                                    <div class="col-xs-3">
                                        <button type="reset" class="btn btn-default">重置</button>
                                        <button type="button" class="btn btn-success search_btn">搜索</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                        <div class="col-md-3 overlay" id="refresh">
                            <i class="fa fa-spinner fa-spin"></i>
                        </div>
                    </div>

                    <div class="-box-content">

                    </div>
                </div>
                <!-- /.box -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>
    <!-- /.content -->
</div>
<?php include APP_PATH . '/views/'.strtolower(APP_NAME).'/include/foot.phtml'; ?>
<script>
    $(function () {
        // 搜索
        $('.search_btn').click(function () {
            var form = $(this).parents('.search-form'), formData = form.serialize(),
                url = $(".nav-tabs .active a").attr('href');
            $('.-box-content').html('');
            $('#refresh').show();
            $.post(url, formData,function(data){
                $('.-box-content').html(data);
                $('#refresh').hide();
                return false;
            });
            return false;
        });

        // 导出
        $('.search-form').submit(function () {
            var url = $(".nav-tabs .active a").attr('href');
            $(this).attr('action',url);
        });

        // 查看详情
        $(".-box-content").on('click','.btn-edit',function () {
            var url = $(this).attr('url');
            $(".tabs-modify").find("a").attr("href", url);
            $(".tabs-modify").click().show();
        });

        // 检测必填字段
        function checkFormRequired(self) {
            if(!self) return true;
            var inx = 0;
            self.find(".required_box").each(function () {
                var self = $(this), input = self.find('input').length?self.find('input'):self.find('select');
                var check = self.attr('check');
                if(!input.val()){
                    self.addClass("has-error");
                    if (inx == 0) {
                        input.focus();
                        inx++;
                    }
                }else{
                    if(check){
                        var val = input.val();
                        var is_check = true;
                        switch (check) {
                            case 'phone':
                                if(!/^1[3-9]\d{9}$/.test(val)){
                                    is_check = false;
                                    inx++;
                                }
                                break;
                            case 'money':
                                var check_val = parseFloat(self.attr('check_val'));
                                if(parseFloat(val) > check_val ) {
                                    is_check = false;
                                    inx++;
                                }
                                break;
                            default:
                                break;
                        }
                        if(is_check){
                            self.find('.text-red').hide();
                            self.removeClass("has-error");
                        }else{
                            self.find('.text-red').show();
                            self.addClass("has-error");
                        }
                    }else {
                        self.removeClass("has-error");
                    }
                }
            });

            return (inx==0)?true:false;
        }

        // 添加规格值
        $(".-box-content").on('click','.add_btn',function () {
            var form_group = $(this).parents('.form-group'),
                form_group_new = form_group.clone(true),
                btn_new = form_group_new.find('.btn');
            form_group_new.find('input').val('');
            form_group.after(form_group_new);
            btn_new.removeClass('add_btn').addClass('del_btn');
            btn_new.find('i').removeClass('fa-plus').addClass('fa-minus').text('删除规格值');
            form_group_new.find('.one_label').remove();
        });
        // 删除规格值
        $(".-box-content").on('click','.del_btn',function () {
            $(this).parents('.form-group').remove();
        });
    })
</script>