<?php include APP_PATH . '/views/'.strtolower(APP_NAME).'/include/head.phtml'; ?>
<div class="content-wrapper">
    <!-- Content Header (页眉) -->
    <section class="content-header">
        <h1>
            营销
            <small>会员折扣</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-th"></i> 营销</a></li>
            <li class="active">会员折扣</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="nav-tabs-custom">
                    <ul class="nav nav-tabs" finish-status="true">
                        <li search-class="all_list"><a href="/crm/list">会员折扣</a></li>
                        <li search-class="other_list"><a href="/crm/modify">添加折扣</a></li>
                        <li class="tabs-modify" style="display: none"><a href="/crm/modify">编辑折扣</a></li>
                    </ul>

                    <div class="box-body">
                        <div class="search-body all_list">
                            <form method="post" action="" class="search-form">
                                <div class="row">
                                    <div class="col-xs-3">
                                        <div class="input-group">
                                            <div class="input-group-btn">
                                                <button type="button" class="btn btn-default">ID</button>
                                            </div><!-- /btn-group -->
                                            <input type="text" class="form-control" name='id' value="" placeholder="ID">
                                        </div>
                                    </div>
                                    <div class="col-xs-3">
                                        <div class="input-group">
                                            <div class="input-group-btn">
                                                <button type="button" class="btn btn-default">折扣名称</button>
                                            </div><!-- /btn-group -->
                                            <input type="text" class="form-control" name='name' value="" placeholder="折扣名称">
                                        </div>
                                    </div>
                                    <div class="col-xs-3">
                                        <button type="reset" class="btn btn-default">重置</button>
                                        <button type="button" class="btn btn-success search_btn">搜索</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                        <div class="col-md-3 overlay" id="refresh">
                            <i class="fa fa-spinner fa-spin"></i>
                        </div>
                    </div>

                    <div class="-box-content">

                    </div>
                </div>
                <!-- /.box -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>
    <!-- /.content -->
</div>
<?php include APP_PATH . '/views/'.strtolower(APP_NAME).'/include/foot.phtml'; ?>
<script>
    $(function () {
        // 搜索
        $('.search_btn').click(function () {
            var form = $(this).parents('.search-form'), formData = form.serialize(),
                url = $(".nav-tabs .active a").attr('href');
            $('.-box-content').html('');
            $('#refresh').show();
            $.post(url, formData,function(data){
                $('.-box-content').html(data);
                $('#refresh').hide();
                return false;
            });
            return false;
        });

        // 表单提交
        $(".-box-content").on('click', '.modify_btn', function () {
            var fromObj = $("#modify_form");
            if(checkFormRequired(fromObj)){
                var idArr = [], items_yes = $("input[name=items_yes]").val(),
                    items = '';
                $('.id-checkbox:checked').each(function () {
                    idArr.push($(this).val());
                });
                items = items_yes;
                if(items){
                    if(idArr.length){
                        items += ','+idArr.join(',');
                    }
                }else {
                    if (!idArr.length) {
                        alert('请选择商品！');
                        return false;
                    }
                    items = idArr.join(',');
                }
                var url = fromObj.attr('action'), postData = new FormData(fromObj[0]);
                postData.append('items', items);
                if(url && postData){
                    $.ajax({
                        url: url,
                        type:'POST',
                        cache:false,
                        data: postData,
                        processData:false,
                        contentType:false
                    }).done(function (data) {
                        if (data.code == 200){
                            $(".nav-tabs-custom .nav-tabs li:first").click();
                        } else{
                            alert(data.msg);
                        }
                    }).fail(function (data) {
                        alert('请求失败');
                    });
                }
            }
            return false;
        });

        // 编辑
        $(".-box-content").on('click','.btn-edit',function () {
            var url = $(this).attr('url');
            $(".tabs-modify").find("a").attr("href", url);
            $(".tabs-modify").click().show();
        });

        // 检测必填字段
        function checkFormRequired(obj){
            if(!obj) return true;
            var inx = 0;
            obj.find(".required_box").each(function () {
                var self = $(this), input = self.find('input').length?self.find('input'):self.find('select');
                var check = self.attr('check'), val = input.val();
                if(!val){
                    self.addClass("has-error");
                    if (inx == 0) {
                        input.focus();
                    }
                    inx++;
                }else {
                    var select = self.find('select');
                    if (select.length && !select.val()) {
                        self.find('.text-red').html('请选择会员等级').show();
                        self.addClass("has-error");
                        if (inx == 0) {select.focus();}
                        inx++;
                    }else if(check && (parseFloat(val)<1 || parseFloat(val)>10)){
                        self.find('.text-red').html('折扣值范围只能1~10').show();
                        self.addClass("has-error");
                        if (inx == 0) {input.focus();}
                        inx++;
                    }else {
                        self.removeClass("has-error");
                        self.find('.text-red').hide();
                    }
                }
            });

            return (inx==0)?true:false;
        }

        // 添加规格值
        $(".-box-content").on('click','.add_btn',function () {
            var form_group = $(this).parents('.form-group'),
                form_group_new = form_group.clone(true),
                btn_new = form_group_new.find('.btn');
            form_group_new.find('input').val('');
            form_group_new.find('select').val('');
            form_group.parent().append(form_group_new);
            form_group_new.find('.control-label').html('');
            btn_new.removeClass('add_btn').addClass('del_btn');
            btn_new.find('i').removeClass('fa-plus').addClass('fa-minus').text('移除折扣');
            form_group_new.find('.one_label').remove();
        });
        // 删除规格值
        $(".-box-content").on('click','.del_btn',function () {
            $(this).parents('.form-group').remove();
        });

        // 修改页面搜索
        $(".-box-content").on('click','.search_btn',function () {
            var form = $(this).parents('.search-form'),
                formData = form.serialize(),
                discount_info = form.parents(".discount_info"),
                url = discount_info.attr('url'),
                discount_body = discount_info.find('.discount_body'),
                refresh = discount_info.find("#refresh_in");
            discount_body.html('');
            refresh.show();
            $.post(url, formData,function(data){
                refresh.hide();
                discount_body.html(data);
                return false;
            });
            return false;
        })

    })
</script>