<?php include APP_PATH . '/views/'.strtolower(APP_NAME).'/include/head.phtml'; ?>
<div class="content-wrapper">
    <!-- Content Header (页眉) -->
    <section class="content-header">
        <h1>
            营销
            <small>礼品中心</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-th"></i> 营销</a></li>
            <li class="active">礼品中心</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="nav-tabs-custom">
                    <ul class="nav nav-tabs" finish-status="true">
                        <li search-class="all_list"><a href="/gift/list">赠礼中心</a></li>
                        <li><a href="/card/list">贺卡</a></li>
                        <li><a href="/bless/list">祝福语</a></li>
                        <li class="tabs-modify" style="display: none"><a href="/gift/modify">赠礼详情</a></li>
                    </ul>

                    <div class="box-body">
                        <div class="search-body all_list">
                            <form method="post" action="" class="search-form">
                                <div class="row" style="margin-bottom: 15px">
                                    <div class="col-xs-3">
                                        <div class="input-group">
                                            <div class="input-group-btn">
                                                <button type="button" class="btn btn-default">赠送人</button>
                                            </div><!-- /btn-group -->
                                            <input type="text" class="form-control" name='buyerName' value="" placeholder="赠送人">
                                        </div>
                                    </div>
                                    <div class="col-xs-3">
                                        <div class="input-group">
                                            <div class="input-group-btn">
                                                <button type="button" class="btn btn-default">获赠人</button>
                                            </div><!-- /btn-group -->
                                            <input type="text" class="form-control" name='receiverName' value="" placeholder="获赠人">
                                        </div>
                                    </div>
                                    <div class="col-xs-3">
                                        <div class="input-group">
                                            <div class="input-group-btn">
                                                <button type="button" class="btn btn-default">商品名称</button>
                                            </div><!-- /btn-group -->
                                            <input type="text" class="form-control" name='itemName' value="" placeholder="商品名称">
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-xs-3">
                                        <div class="input-group">
                                            <div class="input-group-btn">
                                                <button type="button" class="btn btn-default">礼品ID</button>
                                            </div><!-- /btn-group -->
                                            <input type="text" class="form-control" name='id' value="" placeholder="礼品ID">
                                        </div>
                                    </div>
                                    <div class="col-xs-3">
                                        <div class="input-group">
                                            <div class="input-group-btn">
                                                <button type="button" class="btn btn-default">礼品状态</button>
                                            </div><!-- /btn-group -->
                                            <select class="form-control" name="status">
                                                <option value="">选择商品分类</option>
                                                <?php if(!empty($statusArr)):?>
                                                <?php foreach ($statusArr as $k=>$v):?>
                                                <option value="<?=$k?>"><?=$v?></option>
                                                <?php endforeach;?>
                                                <?php endif;?>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="col-xs-3">
                                        <button type="reset" class="btn btn-default">重置</button>
                                        <button type="button" class="btn btn-success search_btn">搜索</button>
                                    </div>
                                </div>
                            </form>
                        </div>

                        <div class="col-md-3 overlay" id="refresh">
                            <i class="fa fa-spinner fa-spin"></i>
                        </div>

                        <div class="-box-content"></div>
                    </div>
                </div>
                <!-- /.box -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>
    <!-- /.content -->
</div>
<?php include APP_PATH . '/views/'.strtolower(APP_NAME).'/include/foot.phtml'; ?>
<script>
    $(function () {
        // 搜索
        $('.search_btn').click(function () {
            var form = $(this).parents('.search-form'), formData = form.serialize(),
                url = $(".nav-tabs .active a").attr('href');
            $('.-box-content').html('');
            $('#refresh').show();
            $.post(url, formData,function(data){
                $('.-box-content').html(data);
                $('#refresh').hide();
                return false;
            });
            return false;
        });

        // 查看详情
        $(".-box-content").on('click','.btn-edit',function () {
            var url = $(this).attr('url');
            $(".tabs-modify").find("a").attr("href", url);
            $(".tabs-modify").click().show();
        });

        // 重新上传
        $(".-box-content").on('click', '.card_repeat, .add_card', function () {
            var parent = $(this).parent(),
                card_id = parent.attr('card_id'),
                pic_url = parent.attr('pic_url');
            if(!card_id) card_id = '';
            if(!pic_url) pic_url = '';
            $('.card_dialog').find("input[name=picUrl]").val("");
            $('.card_dialog').find("input[name=card_id]").val(card_id);
            $('.card_dialog').find("#img_file").attr('src',pic_url);
            $('.card_dialog').find("input[name=picUrl_old]").val(pic_url);
        });

        // 弹窗保存操作
        $(".-box-content").on('click','.save_dialog_btn',function () {
           var self = $(this),form = self.parents('.modal').find('form'),
               url = form.attr('action'), input = form.find('input[name=picUrl]');
               postData = new FormData(form[0]);
           if(!input.val()){
               alert('请选择上传图片');return false;
           }else{
               var size = input[0].files[0].size, sizeLimit = input.attr('size-limit');
               if(size>1024*parseInt(sizeLimit)){
                   input.parent().find('.text-red').show();return false;
               }else{
                   input.parent().find('.text-red').hide();
               }
           }
            if(url && postData){
                $.ajax({
                    url: url,
                    type:'POST',
                    cache:false,
                    data: postData,
                    processData:false,
                    contentType:false
                }).done(function (data) {
                    if (data.code == 200){
                        self.parents('.modal').modal('hide');  // 去除弹窗
                        $(".nav-tabs .active").removeClass("active").click().show();
                    } else{
                        if(data.msg){
                            alert(data.msg)
                        }else{
                            alert('系统已退出或系统错误');
                        }
                    }
                }).fail(function (data) {
                    alert('请求失败');
                });
            }
            return false;
        });

        // 删除
        $(".-box-content").on('click','.remove_btn',function () {
            var url = $(this).attr('url'), box_field = $(this).parents('.box_field');
            if(url && confirm('确认删除？')){
                $.post(url, function (data) {
                    if(data.code == 200){
                        box_field.remove();
                    }else{
                        if(data.msg){
                            alert(data.msg)
                        }else{
                            alert('系统已退出或系统错误');
                        }
                    }
                })
            }
        });

        // 新增祝福语
        $(".-box-content").on('click','.edit_bless,.add_bless',function () {
            var parent = $(this).parent(),
                bless_id = parent.attr('bless_id'),
                bless = parent.attr('bless');
            if(!bless_id) bless_id = '';
            if(!bless) bless = '';
            $('.bless_dialog').find("textarea[name=bless]").val(bless);
            $('.bless_dialog').find("input[name=bless_id]").val(bless_id);
        })

        // 保存祝福语
        $(".-box-content").on('click','.save_dialog_btn_bless',function () {
            var self = $(this),form = self.parents('.modal').find('form'),
                url = form.attr('action'), textarea = form.find('textarea[name=bless]');
            postData = new FormData(form[0]);
            if(!textarea.val()){
                alert('请填写祝福语');return false;
            }else{
                if (textarea.val().length>40){
                    alert('祝福语字数太长');return false;
                }
            }
            if(url && postData){
                $.ajax({
                    url: url,
                    type:'POST',
                    cache:false,
                    data: postData,
                    processData:false,
                    contentType:false
                }).done(function (data) {
                    if (data.code == 200){
                        self.parents('.modal').modal('hide');  // 去除弹窗
                        $(".nav-tabs .active").removeClass("active").click().show();
                    } else{
                        if(data.msg){
                            alert(data.msg)
                        }else{
                            alert('系统已退出或系统错误');
                        }
                    }
                }).fail(function (data) {
                    alert('请求失败');
                });
            }
            return false;
        });

    })
</script>