<div class="box-body">
    <form id="modify_form" class="form-horizontal" action="/poster/update" method="post" enctype="multipart/form-data">
        <div class="box-body">
            <div class="form-group has-success required_box">
                <label for="" class="col-sm-2 control-label"><i class="fa fa-check-circle">(必填)</i>模板图片</label>
                <div class="col-sm-5">
                    <input name="picUrl" id="input_file" type="file" size-limit="500" >
                    <img id="img_file" src="<?=$data['picUrl']?>" height="50" />
                    <span class="text-red" style="display: none">图片大小不能超过500kb</span>
                </div>
                <label class="control-label" data-toggle="tooltip" title="" data-original-title="请上传500kb以内；建议图片尺寸为750px*630px；格式为jpeg,jpg,png的图片"><i class="fa fa-info-circle"></i><label/>
            </div>
            <div class="form-group">
                <label for="" class="col-sm-2 control-label">是否启用</label>
                <div class="col-sm-10">
                    <div class="checkbox">
                        <label style="padding-left: 0;">
                            <input <?php if($data['open']):?>checked<?php endif;?> value="2" checked name="open" type="radio"> 是
                        </label>
                        <label>
                            <input <?php if(!$data['open']):?>checked<?php endif;?> value="1" name="open" type="radio"> 否
                        </label>
                    </div>
                </div>
            </div>
        </div>
        <!-- /.box-body -->
        <div class="box-footer">
            <button type="submit" class="btn btn-primary">提交</button>
            <?php if (!empty($data)):?>
                <input type="hidden" name="id" value="<?=$data['id']?>">
                <input type="hidden" id="icon_file" name="picUrl" value="<?=$data['picUrl']?>">
            <?php endif;?>
        </div>
        <!-- /.box-footer -->
    </form>
</div>