<?php include APP_PATH . '/views/'.strtolower(APP_NAME).'/include/head.phtml'; ?>
    <div class="content-wrapper">
        <!-- Content Header (页眉) -->
        <section class="content-header">
            <h1>
                商品
                <small>模板管理</small>
            </h1>
            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-gift"></i> 商品</a></li>
                <li class="active">模板管理</li>
            </ol>
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="row">
                <div class="col-xs-12">
                    <div class="nav-tabs-custom">
                        <ul class="nav nav-tabs" finish-status="true">
                            <li search-class="poster-list"><a href="/poster/list">模板管理</a></li>
                            <li class="tabs-modify add_poster" style="display: none"><a href="/poster/modify">新增模板</a></li>
                            <li class="tabs-modify edit_poster" style="display: none"><a href="/poster/modify">修改模板</a></li>
                        </ul>

                        <div class="box-body">
                            <div class="search-body poster-list">
                                <div class="row">
                                    <div class="col-xs-10"></div>
                                    <div class="col-xs-2">
                                        <button type="button" class="btn btn-success" id="add_poster">新增模板</button>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-3 overlay" id="refresh">
                                <i class="fa fa-spinner fa-spin"></i>
                            </div>
                        </div>

                        <div class="-box-content">

                        </div>
                    </div>
                    <!-- /.box -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </section>
        <!-- /.content -->
    </div>
<?php include APP_PATH . '/views/'.strtolower(APP_NAME).'/include/foot.phtml'; ?>
<script>
    $(function () {
        // 新增模板
        $("#add_poster").click(function () {
            $(".add_poster").click().show();
        });

        // 检测必填字段
        function checkFormRequired(self) {
            if(!self) return true;
            var inx = 0;
            self.find(".required_box").each(function () {
                var input = $(this).find('input').length ? $(this).find('input') : $(this).find('select'),
                    fa = $(this).find('.fa'), type = input.attr('type');
                if(!input.val()){
                    if(type == 'file' && $("#icon_file").val()){
                        $(this).removeClass("has-error").addClass("has-success");
                        fa.removeClass("fa-times-circle").addClass("fa-check-circle");
                    }else {
                        $(this).removeClass("has-success").addClass("has-error");
                        fa.removeClass("fa-check-circle").addClass("fa-times-circle");
                        if (inx == 0) {
                            input.focus();
                            inx++;
                        }
                    }
                }else{
                    $(this).removeClass("has-error").addClass("has-success");
                    fa.removeClass("fa-times-circle").addClass("fa-check-circle");
                    if(type == 'file'){  // 判断图片大小
                        var size = input[0].files[0].size, sizeLimit = input.attr('size-limit');
                        if(size>1024*parseInt(sizeLimit)){
                            input.parent().find('.text-red').show();
                            if(inx==0){
                                input.focus();inx++;
                            }
                        }else{
                            input.parent().find('.text-red').hide();
                        }
                    }
                }
            });

            return (inx==0)?true:false;
        }

        // 表单提交
        $(".-box-content").on('submit', '#modify_form', function () {
            if(checkFormRequired($(this))){
                var self = $(this), url = self.attr('action'), postData = new FormData(self[0]);
                if(url && postData){
                    $.ajax({
                        url: url,
                        type:'POST',
                        cache:false,
                        data: postData,
                        processData:false,
                        contentType:false
                    }).done(function (data) {
                        if (data.code == 200){
                            $(".nav-tabs-custom .nav-tabs li:first").click();
                        } else{
                            alert(data.msg);
                        }
                    }).fail(function (data) {
                        alert('请求失败');
                    });
                }
            }
            return false;
        });

        // 编辑按钮操作
        $(".-box-content").on('click','.btn-edit',function () {
            var form = $(this).parent().find('.edit_form'),
                formData = form.serialize(), action = form.attr('action'),
                href = action+"?"+formData;
            $(".edit_poster").find("a").attr("href", href);
            $(".edit_poster").click().show();
        });

    })
</script>
