<div class="box-body">
    <form class="form-horizontal">
        <div class="box-body">
            <div class="form-group has-success">
                <label for="" class="col-sm-2 control-label"><i class="fa fa-check-circle">(必填)</i>商品名称</label>

                <div class="col-sm-5">
                    <input type="text" class="form-control" id="" placeholder="商品名称">
                </div>
            </div>
            <div class="form-group has-success">
                <label for="" class="col-sm-2 control-label"><i class="fa fa-check-circle">(必填)</i>商品分类</label>
                <div class="col-sm-5">
                    <select class="form-control">
                        <option>选项 1</option>
                        <option>选项 2</option>
                    </select>
                </div>
            </div>
            <div class="form-group">
                <label for="" class="col-sm-2 control-label">是否推荐</label>
                <div class="col-sm-5">
                    <div class="checkbox">
                        <label>
                            <input type="checkbox"> 加入推荐
                        </label>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <label for="" class="col-sm-2 control-label">商品标签</label>
                <div class="col-sm-5">
                    <select class="form-control">
                        <option>选项 1</option>
                        <option>选项 2</option>
                    </select>
                </div>
            </div>
            <div class="form-group has-success">
                <label for="" class="col-sm-2 control-label"><i class="fa fa-check-circle">(必填)</i>商品售价</label>
                <div class="col-sm-5">
                    <input type="text" class="form-control" id="" placeholder="商品售价">
                </div>
            </div>
            <div class="form-group">
                <label for="" class="col-sm-2 control-label">设为礼品</label>
                <div class="col-sm-10">
                    <div class="checkbox">
                        <label>
                            <input type="checkbox"> 支持送礼
                            <span class="text-yellow"> <i class="fa fa-bullhorn"></i>礼品需包邮且在小程序商城礼品赠送区域</span>
                        </label>
                    </div>
                </div>
            </div>

            <div class="box">
                <div class="box-header">
                    <h4 class="box-title">商品规格</h4>
                    <div class="form-group">
                        <label for="" class="col-sm-2 control-label">一级规格名</label>
                        <div class="col-sm-3">
                            <select class="form-control select-input" id_name="one_sku_name" sku_name="1">
                                <option value="">请选择</option>
                                <option value="系列">系列</option>
                                <option value="选项">选项</option>
                            </select>
                            <input id_name="one_sku_name" sku_name="1" type="text" class="form-control sku_input" name="skuNameOne" maxlength="4" style="position:absolute;width: 70%;top: 0;">
                        </div>
                        <label class="control-label" data-toggle="tooltip" title="" data-original-title="仅支持为第一组规格设置规格图片，买家选择不同规格会看到对应规格图片，建议尺寸：800 x 800像素"><i class="fa fa-info-circle"></i></label>
                    </div>
                    <div class="form-group">
                        <label for="" class="col-sm-2 control-label">规格值</label>
                        <div class="col-sm-3 tr_num_one">
                            <select class="form-control select-input">
                                <option value="">请选择</option>
                                <option value="夏之味蕾">夏之味蕾</option>
                                <option value="冬之催眠">冬之催眠</option>
                            </select>
                            <input type="text" class="form-control sku_input" name="skuValOne[]" maxlength="6" style="position:absolute;width: 70%;top: 0;">
                        </div>
                        <div class="col-sm-3">
                            <input type="file">
                        </div>
                        <div class="col-sm-3">
                            <button type="button" class="btn btn-default add_btn skuValOne"><i class="fa fa-plus">添加规格值</i></button>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="" class="col-sm-2 control-label">二级规格名</label>
                        <div class="col-sm-3">
                            <select class="form-control select-input" id_name="two_sku_name" sku_name="2">
                                <option value="">请选择</option>
                                <option value="口味">口味</option>
                                <option value="选项">选项</option>
                            </select>
                            <input id_name="two_sku_name" type="text" class="form-control sku_input" name="skuNameTwo" maxlength="4" style="position:absolute;width: 70%;top: 0;">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="" class="col-sm-2 control-label">规格值</label>
                        <div class="col-sm-3 tr_num_two">
                            <select class="form-control select-input">
                                <option value="">请选择</option>
                                <option value="海鲜味">海鲜味</option>
                                <option value="孜然味">孜然味</option>
                            </select>
                            <input type="text" class="form-control sku_input" name="skuValTwo[]" maxlength="6" style="position:absolute;width: 70%;top: 0;">
                        </div>
                        <div class="col-sm-3">
                            <button type="button" class="btn btn-default add_btn"><i class="fa fa-plus">添加规格值</i></button>
                        </div>
                    </div>
                </div>
                <div class="sku-info" style="display: none">
                    <div class="box-body">
                        <table class="table table-bordered">
                            <thead>
                            <tr style="background: #eee">
                                <th id="one_sku_name"></th>
                                <th id="two_sku_name"></th>
                                <th><span class="text-red">*</span>库存</th>
                                <th>重量(kg)</th>
                                <th><span class="text-red">*</span>售价(元)</th>
                            </tr>
                            </thead>
                            <tbody>
                            </tbody></table>
                    </div>
                    <div class="box-footer clearfix" style="border: none;">
                    <div class="form-group">
                        <label for="" class="col-sm-2 control-label">批量设置</label>
                        <div class="col-sm-5 btn-group">
                                <button type="button" class="btn btn-default text-blue">编辑</button>
                                <button type="button" class="btn btn-default text-blue">二维码</button>
                                <button type="button" class="btn btn-default text-blue">删除</button>
                        </div>
                    </div>
                </div>
                </div>
            </div>

            <div class="form-group has-success">
                <label for="" class="col-sm-2 control-label"><i class="fa fa-check-circle">(必填)</i>商品库存</label>

                <div class="col-sm-5">
                    <input type="text" class="form-control" id="" placeholder="商品库存">
                </div>
            </div>
            <div class="form-group has-success">
                <label for="" class="col-sm-2 control-label"><i class="fa fa-check-circle">(必填)</i>运费计算</label>
                <div class="col-sm-5">
                    <select class="form-control">
                        <option>选项 1</option>
                        <option>选项 2</option>
                    </select>
                </div>
                <label class="text-yellow control-label"> <i class="fa fa-bullhorn"></i>若按重量计费类模板，请务必填写商品重量<label/>
            </div>

            <div class="form-group has-success">
                <label for="" class="col-sm-2 control-label"><i class="fa fa-check-circle">(必填)</i>商品封面图</label>
                <div class="col-sm-5">
                    <input type="file">
                </div>
                <label class="control-label" data-toggle="tooltip" title="" data-original-title="请上传500kb以内；建议图片尺寸为750px*630px；格式为jpeg,jpg,png的图片"><i class="fa fa-info-circle"></i><label/>
            </div>

            <div class="form-group has-success">
                <label for="" class="col-sm-2 control-label"><i class="fa fa-check-circle">(必填)</i>商品相册</label>
                <div class="col-sm-5">
                    <input type="file"><p class="help-block">相册1</p>
                    <input type="file"><p class="help-block">相册2</p>
                    <input type="file"><p class="help-block">相册3</p>
                    <input type="file"><p class="help-block">相册4</p>
                    <input type="file"><p class="help-block">相册5</p>
                    <input type="file"><p class="help-block">相册6</p>
                </div>
                <label class="control-label" data-toggle="tooltip" title="" data-original-title="请上传500kb以内；建议图片尺寸为750px*630px；格式为jpeg,jpg,png的图片"><i class="fa fa-info-circle"></i></label>
            </div>

            <div class="form-group">
                <label for="" class="col-sm-2 control-label">库存警告</label>
                <div class="col-sm-5">
                    <input type="text" class="form-control" id="" placeholder="库存警告">
                </div>
            </div>
            <div class="form-group">
                <label for="" class="col-sm-2 control-label">产地</label>
                <div class="col-sm-5">
                    <input type="text" class="form-control" id="" placeholder="产地">
                </div>
            </div>
            <div class="form-group">
                <label for="" class="col-sm-2 control-label">储存条件</label>
                <div class="col-sm-5">
                    <input type="text" class="form-control" id="" placeholder="储存条件">
                </div>
            </div>
            <div class="form-group">
                <label for="" class="col-sm-2 control-label">商品品牌</label>
                <div class="col-sm-5">
                    <input type="text" class="form-control" id="" placeholder="商品品牌">
                </div>
            </div>
            <div class="form-group">
                <label for="" class="col-sm-2 control-label">商品详情</label>
                <div class="col-sm-10" id="editor"></div>
            </div>
        </div>
        <!-- /.box-body -->
        <div class="box-footer">
            <button type="submit" class="btn btn-primary">提交</button>
        </div>
        <!-- /.box-footer -->
    </form>
</div>
<script>
    var E = window.wangEditor;
    var editor = new E('#editor');
    editor.customConfig.uploadImgServer = '/product/uploadImage'; //上传URL
    editor.customConfig.uploadImgMaxSize = 1 * 1024 * 1024;
    editor.customConfig.uploadImgMaxLength = 10;
    editor.customConfig.uploadFileName = 'myFileName';
    editor.customConfig.uploadImgHooks = {
        customInsert: function (insertImg, result) {

            // 图片上传并返回结果，自定义插入图片的事件（而不是编辑器自动插入图片！！！）
            // insertImg 是插入图片的函数，editor 是编辑器对象，result 是服务器端返回的结果

            // 举例：假如上传图片成功后，服务器端返回的是 {url:'....'} 这种格式，即可这样插入图片：
            var url = result.data;
            //insert();
            insertImg(url);
            //insertImg('https://ss0.bdstatic.com/5aV1bjqh_Q23odCf/static/superman/img/logo/bd_logo1_31bdc765.png');

            // result 必须是一个 JSON 格式字符串！！！否则报错
        }
    };
    editor.create();
</script>