<?php include APP_PATH . '/views/'.strtolower(APP_NAME).'/include/head.phtml'; ?>
<div class="content-wrapper">
    <!-- Content Header (页眉) -->
    <section class="content-header">
        <h1>
            商品
            <small>商品管理</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-gift"></i> 商品</a></li>
            <li class="active">商品管理</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="nav-tabs-custom">
                    <ul class="nav nav-tabs" finish-status="true">
                        <li search-class="product-list"><a href="/product/list">商品列表</a></li>
                        <li><a href="/product/add">添加商品</a></li>
                        <li search-class="product-trash"><a href="/product/trash">回收站</a></li>
                        <li class="tabs-modify" style="display: none"><a href="/product/modify">编辑商品</a></li>
                    </ul>

                    <div class="box-body">
                        <div class="search-body product-list">
                            <form method="post" action="/product/list" class="search-form">
                            <div class="row">
                                <div class="col-xs-4">
                                    <div class="input-group">
                                        <div class="input-group-btn">
                                            <button type="button" class="btn btn-default">商品名称</button>
                                        </div><!-- /btn-group -->
                                        <input type="text" class="form-control" name='name' value="" placeholder="商品名称">
                                    </div>
                                </div>
                                <div class="col-xs-4">
                                    <div class="input-group">
                                        <div class="input-group-btn">
                                            <button type="button" class="btn btn-default">商品ID</button>
                                        </div><!-- /btn-group -->
                                        <input type="text" class="form-control" name='id' value="" placeholder="商品ID">
                                    </div>
                                </div>
                                <div class="col-xs-3">
                                    <div class="input-group">
                                        <div class="input-group-btn">
                                            <button type="button" class="btn btn-default">商品分类</button>
                                        </div><!-- /btn-group -->
                                        <select class="form-control" name='cid'>
                                            <option value="0" selected>全部</option>
                                            <?php if(!empty($cats)):?>
                                            <?php foreach ($cats as $k=>$v):?>
                                            <option value="<?=$k?>" ><?=$v?></option>
                                            <?php endforeach;?>
                                            <?php endif;?>
                                        </select>
                                    </div>
                                </div>
                            </div>
                            <div class="row" style="margin-top: 10px;">
                                <div class="col-xs-3">
                                    <div class="input-group">
                                        <div class="input-group-btn">
                                            <button type="button" class="btn btn-default">商品类型</button>
                                        </div><!-- /btn-group -->
                                        <select class="form-control" name='typeid'>
                                            <option value="0" selected>全部</option>
                                            <option value="1" >商品</option>
                                            <option value="2" >礼品</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="col-xs-2">
                                    <button type="submit" class="btn btn-success">搜索</button>
                                </div>
                            </div>
                        </form>
                        </div>
                        <div class="search-body product-trash">
                            <form method="post" action="/product/trash" class="search-form">
                                <div class="row">
                                    <div class="col-xs-3">
                                        <div class="input-group">
                                            <div class="input-group-btn">
                                                <button type="button" class="btn btn-default">商品名称</button>
                                            </div><!-- /btn-group -->
                                            <input type="text" class="form-control" name='name' value="" placeholder="商品名称">
                                        </div>
                                    </div>
                                    <div class="col-xs-3">
                                        <div class="input-group">
                                            <div class="input-group-btn">
                                                <button type="button" class="btn btn-default">商品ID</button>
                                            </div><!-- /btn-group -->
                                            <input type="text" class="form-control" name='id' value="" placeholder="商品ID">
                                        </div>
                                    </div>
                                    <div class="col-xs-3">
                                        <div class="input-group">
                                            <div class="input-group-btn">
                                                <button type="button" class="btn btn-default">商品分类</button>
                                            </div><!-- /btn-group -->
                                            <select class="form-control" name='cid'>
                                                <option value="0" selected>全部</option>
                                                <?php if(!empty($cats)):?>
                                                    <?php foreach ($cats as $k=>$v):?>
                                                        <option value="<?=$k?>" ><?=$v?></option>
                                                    <?php endforeach;?>
                                                <?php endif;?>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="col-xs-2">
                                        <button type="submit" class="btn btn-success">搜索</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                        <div class="col-md-3 overlay" id="refresh">
                            <i class="fa fa-spinner fa-spin"></i>
                        </div>
                    </div>

                    <div class="-box-content">

                    </div>
                </div>
                <!-- /.box -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>
    <!-- /.content -->
</div>
<?php include APP_PATH . '/views/'.strtolower(APP_NAME).'/include/foot.phtml'; ?>
<script type="text/javascript" src="/js/wangEditor.js"></script>
<script>
    $(function () {
        // 全选
        $(".-box-content").on('click','#check-all', function () {
            $('.id-checkbox').prop('checked', $(this).prop('checked'));
        });

        // 批量操作
        $(".-box-content").on('click','#bulk-ajax',function () {
            var self = $(this),
                url = self.attr('url'),
                select = $('.bulk-select option:selected'),
                title = select.text(),
                type = select.val(), idArr = [];
            $('.id-checkbox:checked').each(function () {
                idArr.push($(this).val());
            });
            if (!url) {alert('参数错误');return;}
            if (0==type){alert('请选择批量操作方式');return;}
            if (!idArr.length){alert('请选择要批量操作的对象');return;}
            if(!title || !confirm('确认执行【'+title+'】')) return;
            var ids = idArr.join(',');
            $.post(url, {type:type,ids:ids},function (data) {
                alert(data.msg);
                if (data.code == 200){
                    if(self.hasClass('reload')) {
                        location.reload();
                    }else {
                        $('.id-checkbox:checked').parent().parent().remove();
                    }
                }
            });
        })

        // 搜索
        $('.search-form').submit(function () {
            var self = $(this);
            $('.-box-content').html('');
            $('#refresh').show();
            $.post(self.attr("action"), self.serialize(),function(data){
                $('.-box-content').html(data);
                $('#refresh').hide();
                return false;
            });
            return false;
        });

        // 编辑
        $(".-box-content").on('click','.btn-edit',function () {
            $(".tabs-modify").click().show();
        })

        // 添加规格值
        $(".-box-content").on('click','.add_btn',function () {
            var form_group = $(this).parents('.form-group'),
                form_group_new = form_group.clone(true);
            form_group_new.find('input').val('');
            form_group.after(form_group_new);
            $(this).removeClass('add_btn').addClass('del_btn');
            $(this).find('i').removeClass('fa-plus').addClass('fa-minus').text('删除规格值');
        });
        // 删除规格值
        $(".-box-content").on('click','.del_btn',function () {
            $(this).parents('.form-group').remove();
            createSkuInfo();
        });
        // 模拟可编辑的select框
        $(".-box-content").on('change','.select-input',function () {
            $(this).parent().find('input').val($(this).val());
            setSkuInfo($(this))
        });

        function setSkuInfo(self) {
            var val = self.val(),
                id_name = self.attr('id_name'),
                sku_name = self.attr('sku_name');
            if(id_name){
                if(sku_name != 1 && val && !$("input[name='skuNameOne']").val()){
                    $("input[name='skuNameOne']").focus();return false;
                }
                $(".sku-info").show();
                $("#"+id_name).text(val);
            }
            createSkuInfo();
            return true;
        }

        function createSkuInfo(){
            var tr_num_one = [], tr_num_two = [];
            $(".tr_num_one input").each(function () {
                tr_num_one.push($(this).val());
            });
            $(".tr_num_two input").each(function () {
                tr_num_two.push($(this).val());
            });
            var html = '';
            for(var i=0; i<tr_num_one.length; i++){
                for(var j=0; j<tr_num_two.length; j++){
                    if(!tr_num_one[i] && !tr_num_two[j]) continue;
                    html += "<tr>";
                    html += "<td>"+tr_num_one[i]+"</td>";
                    html += "<td>"+tr_num_two[j]+"</td>";
                    html += '<td><input type="text"></td><td><input type="text"></td><td><input type="text"></td></tr>';
                }
            }
            $(".sku-info tbody").html(html);
            if(!$("input[name=skuNameOne]").val() && !$("input[name=skuNameOne]").val()) {
                $(".sku-info").hide();
            }
        }

        // 规格信息产生
        $(".-box-content").on('input propertychange', '.sku_input', function () {
            setSkuInfo($(this));
        })
    })
</script>