<footer class="main-footer">
    <!--<div class="pull-right hidden-xs">
        <b>Version</b> 2.3.8
    </div>-->
    <div style="text-align:center;">
        <strong>Copyright &copy; 2014-2018 </strong> 点评微生活(北京)科技股份有限公司. All Rights Reserved | 客服电话：400-600-7660
    </div>
</footer>
<!-- 添加侧边栏的背景。
     这个 div必须放在 control-sidebar 之后 -->
<div class="control-sidebar-bg"></div>
</div>
</body>
</html>