<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>超级消费端商户平台</title>
    <!-- 告诉浏览器该页面是自适应布局 -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.6 -->
    <link rel="stylesheet" href="/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="/css/AdminLTE.min.css">
    <!-- ICheck Green -->
    <link rel="stylesheet" href="/css/green.css">
    <!-- AdminLTE 皮肤 -->
    <link rel="stylesheet" href="/css/_all-skins.min.css">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- 警告：Respond.js 不支持 file:// 方式查看（即本地方式查看）-->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <!-- jQuery 2.2.3 -->
    <script src="/js/jquery-2.2.3.min.js"></script>
    <!-- Bootstrap 3.3.6 -->
    <script src="/js/bootstrap.min.js"></script>
    <!-- AdminLTE App -->
    <script src="/js/app.min.js"></script>
    <script>
        var _ctrl = "ctrl<?=$ctrl_name?>",
            _act = "<?=$action_name?><?=$ctrl_name?>";
    </script>
    <script src="/js/vmall.js"></script>
</head>
<body class="hold-transition skin-blue sidebar-mini">
<!-- Site wrapper -->
<div class="wrapper">

    <header class="main-header">
        <!-- Logo -->
        <a href="/" class="logo">
            <!-- mini logo for sidebar mini 50x50 pixels -->
            <span class="logo-mini">TS</span>
            <!-- logo for regular state and mobile devices -->
            <span class="logo-lg"><?php echo $bBrandName;?></span>
        </a>
        <!-- Header Navbar: style can be found in header.less -->
        <nav class="navbar navbar-static-top">
            <!-- Sidebar toggle button-->
            <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
                <span class="sr-only">切换导航</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>

            <div class="navbar-custom-menu">
                <ul class="nav navbar-nav">
                    <li class="dropdown notifications-menu">
                        <a href="" class="dropdown-toggle">
                            <i class="fa fa-bell-o"></i>
                            <span class="label label-warning" id="msg-cnt"><?php echo $_msgCnt?></span>
                        </a>
                    </li>
                    <li class="dropdown user user-menu">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <img src="/img/avatar.png" class="user-image" alt="用户图像">
                            <span class="hidden-xs"><?php echo $managerName;?></span>
                        </a>
                    </li>
                    <li>
                        <a href="/logout">退出登录 <i class="fa fa-sign-out"></i></a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>

    <!-- =============================================== -->

    <!-- Left side column. contains the sidebar -->
    <aside class="main-sidebar">
        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">
            <!-- sidebar menu: : style can be found in sidebar.less -->
            <ul class="sidebar-menu">
                <li class="header">超级消费端商户平台</li>
                <li class="treeview" id="ctrl_index">
                    <a href="#">
                        <i class="fa fa-bell"></i> <span>通知</span>
                        <span class="pull-right-container">
                          <i class="fa fa-angle-left pull-right"></i>
                        </span>
                    </a>
                    <ul class="treeview-menu">
                        <li id="index_index"><a href="/"><i class="fa fa-circle-o"></i> 消息通知</a></li>
                    </ul>
                </li>
                <li class="treeview" id="ctrl_goods">
                    <a href="#">
                        <i class="fa fa-gift"></i> <span>商品</span>
                        <span class="pull-right-container">
                          <i class="fa fa-angle-left pull-right"></i>
                        </span>
                    </a>
                    <ul class="treeview-menu">
                        <li id="product_goods"><a href="/product"><i class="fa fa-circle-o"></i> 商品管理</a></li>
                        <li id="cat_goods"><a href="/cat"><i class="fa fa-circle-o"></i> 分类管理</a></li>
                        <li id="tag_goods"><a href="/tag"><i class="fa fa-circle-o"></i> 标签管理</a></li>
                        <li id="rate_goods"><a href="/rate"><i class="fa fa-circle-o"></i> 评价管理</a></li>
                        <li id="poster_goods"><a href="/poster"><i class="fa fa-circle-o"></i> 海报模板</a></li>
                    </ul>
                </li>
                <li class="treeview" id="ctrl_trade">
                    <a href="#">
                        <i class="fa fa-edit"></i> <span>订单</span>
                        <span class="pull-right-container">
                          <i class="fa fa-angle-left pull-right"></i>
                        </span>
                    </a>
                    <ul class="treeview-menu">
                        <li id="index_trade"><a href="/trade"><i class="fa fa-circle-o"></i> 订单管理</a></li>
                    </ul>
                </li>
                <li class="treeview">
                    <a href="#">
                        <i class="fa fa-th"></i> <span>营销</span>
                        <span class="pull-right-container">
                          <i class="fa fa-angle-left pull-right"></i>
                        </span>
                    </a>
                    <ul class="treeview-menu">
                        <li><a href="#"><i class="fa fa-circle-o"></i> 会员折扣</a></li>
                        <li><a href="#"><i class="fa fa-circle-o"></i> 礼品中心</a></li>
                    </ul>
                </li>
                <li class="treeview">
                    <a href="#">
                        <i class="fa fa-pie-chart"></i> <span>数据</span>
                        <span class="pull-right-container">
                          <i class="fa fa-angle-left pull-right"></i>
                        </span>
                    </a>
                    <ul class="treeview-menu">
                        <li><a href="#"><i class="fa fa-circle-o"></i> 数据统计</a></li>
                    </ul>
                </li>
                <li class="treeview">
                    <a href="#">
                        <i class="fa fa-gears"></i> <span>商城设置</span>
                        <span class="pull-right-container">
                          <i class="fa fa-angle-left pull-right"></i>
                        </span>
                    </a>
                    <ul class="treeview-menu">
                        <li><a href="#"><i class="fa fa-circle-o"></i> 基础设置</a></li>
                        <li><a href="#"><i class="fa fa-circle-o"></i> 运费模板</a></li>
                        <li><a href="#"><i class="fa fa-circle-o"></i> 门店管理</a></li>
                        <li><a href="#"><i class="fa fa-circle-o"></i> 支付设置</a></li>
                    </ul>
                </li>
            </ul>
        </section>
        <!-- /.sidebar -->
    </aside>